# Generated by Django 5.0.6 on 2024-06-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(blank=True, db_table='authentication_user_permission', related_name='users', to='authentication.permission'),
        ),
    ]
