# Generated by Django 5.0.6 on 2024-06-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='permissions',
            new_name='user_permissions',
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='group',
            name='permissions',
            field=models.ManyToManyField(blank=True, db_table='authentication_group_permission', related_name='groups', to='authentication.permission'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, db_table='authentication_group_user', related_name='groups', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
