# Generated by Django 5.0.6 on 2024-06-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_permissions_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankIDAuthentication',
            fields=[
                ('order_ref', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('auto_start_token', models.CharField(max_length=255)),
                ('qr_start_token', models.CharField(max_length=255)),
                ('qr_start_secret', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bankid_authentication',
            },
        ),
    ]
