# Generated by Django 5.0.6 on 2024-06-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_bankidauthentication'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bankidauthentication',
            table='authentication_bankid',
        ),
    ]
