version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_db_user -d your_db_name"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://your_db_user:your_db_password@db:5432/your_db_name
      - PIPELINE=local

  #frontend:
    #build:
      #context: ./frontend
      #dockerfile: Dockerfile
    #volumes:
      #- ./frontend:/app
    #ports:
      #- "3000:3000"
    #environment:
      #- REACT_APP_BACKEND_URL=http://localhost:8000

volumes:
  postgres_data: